name: Mageia 9 amd64 RPM package

on: [workflow_dispatch]

jobs:
  build-rpm:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Build Docker image
      uses: docker/build-push-action@v6
      with:
        tags: image-mageia-9
        context: ./packages/mageia-9
      env:
        DOCKER_BUILD_SUMMARY: false
        DOCKER_BUILD_RECORD_UPLOAD: false

    - name: Build RPM package
      uses: addnab/docker-run-action@v3
      with:
        image: image-mageia-9
        options: --name container-mageia-9
        run: |
          ./build.sh

    - name: Copy from container to host
      uses: tj-actions/docker-cp@v2
      with:
        container: container-mageia-9
        source: /buildroot
        destination: packages/mageia-9/output

    - name: Upload
      uses: actions/upload-artifact@v4
      with:
        name: Mageia 9 packages
        path: packages/mageia-9/output
        if-no-files-found: error
